# Generated by Django 5.1 on 2025-12-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='fundaiser',
            new_name='fundraiser',
        ),
    ]
