# Generated by Django 5.1 on 2026-02-08 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_fundraiser_deadline_alter_pledge_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 8, 10, 42, 42, 371545, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
