# Generated by Django 5.1 on 2026-02-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0004_pledge_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
